### ISSUE TITLE
Dvorak prints in low-contrast

### ISSUE THREAD

**Issue by excalq** [mattmc3/neovim-cheatsheet#3]
Unfortunately the black-on-purple and even to a lesser degree black-on-teal do not print very ledgibly (on an Epson XP6000, with presentation matte papper).

I'd suggest just keeping the high-contrast black-on-yellow/green as the original.

**Comment by mattmc3** [comment]
Feel free to go to the QWERTY layout, select from the top left escape to the bottom right and copy (eg: ⌘-C on Mac), and then go to whatever destination sheet you want and right click, choose paste special, and format only (eg: ⌘-Option-V on Mac). That will let you get the formatting from whatever sheet you want overlayed onto another sheet.

You may also choose to use [the included javascript generator](https://github.com/mattmc3/neovim-cheatsheet/blob/main/apps-script/cheatsheet-template-generator.js) to create your own formatting better suited to printing.

<img width="439" alt="Screenshot 2024-07-15 at 9 40 48 PM" src="https://github.com/user-attachments/assets/c0dd7b11-77ce-49d4-8570-cfa50c08d76e">
